### ISSUE TITLE
Static file loader with filerev

### ISSUE THREAD

**Issue by sharanmunyal** [angular-translate/bower-angular-translate-loader-static-files#11]
I am working on a page which has assets served by a caching layer. Hence in order to avoid browser serving old files; (in other words in order to ensure modified files are not served from the caching layer), we are using filerev for those asset files. I am having all the language files under assets/lang/ . Hence I was wondering if I can use bower-angular-translate-loader-static-files in some way so that am assured to download strings_{lang_code}.{md5}.json From what I see from the angular-translate-loader-static-files source code, this seems to be a difficult usecase to handle. Let me know if you can think of any workarounds.

**Comment by Frank3K** [comment]
I encountered the same issue. Since I could not think of a solution using any of the standard loaders I resorted to creating a [custom loader](https://angular-translate.github.io/docs/#/guide/13_custom-loaders). This was not that hard as I expected beforehand.

You can view my translationLoader [here](https://gist.github.com/Frank3K/01c946dfef457841b4f8). Bootstrapping is simple (but a tad verbose):

``` js
...
	.config(function($translateProvider) {
		$translateProvider.useLoader('translationLoader', {
			files: [{
				languageKey: 'en',
				localeFile: 'locale/locale-en.json'
			}, {
				....
			}]
		});
	})
...
```

Since each translation file is added separately, [usemin](https://github.com/yeoman/grunt-usemin) can replace the files created by [filerev](https://github.com/yeoman/grunt-filerev).

**Comment by Sjors** [comment]
It would be nice if, perhaps using @Frank3K's code, you can pass the static loader a dictionary of language codes and file paths.

**Comment by knalli** [comment]
Yes, we recommend building a custom loader which is actually very simple to do. You can even delegate and re-use one of the existing loaders (i.e. static-files-loader).

**Comment by knalli** [comment]
Please file any issues in the main repository at https://github.com/angular-translate/angular-translate
