### ISSUE TITLE
bower.io problem with 2.6.1

### ISSUE THREAD

**Issue by evilaliv3** [angular-translate/bower-angular-translate-loader-static-files#13]
performing bower install angular-translate-loader-static-files in relation to the GlobaLeaks project we are getting the following error:

```
ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/PascalPrecht/bower-angular-translate-loader-static-files.git", exit code of #128
```

this is due to the pakage descriptor still including a reference to the repo of @PascalPrecht

**Comment by rodolfobueno** [comment]
+1

**Comment by cvn** [comment]
I experienced this today. It was because I was behind a firewall, not because of the old URL, which does redirect correctly when everything else is working. I found 2 ways to resolve the problem.

1. edit your bower file to force the new URL, e.g.

        "angular-translate-loader-static-files": "git://github.com/angular-translate/bower-angular-translate-loader-static-files.git#^2.11.0"

2. configure git to use https instead of git protocol

        git config --global url."https://".insteadOf git://

This thread contains more context and other things to try if either of these don't work: https://github.com/eschnou/ardrone-webflight/issues/49
